name: Daily Forecast Bot

# give the GITHUB_TOKEN write access so our commit step can push
permissions:
  contents: write

on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate config/settings.yaml
        run: |
          mkdir -p config
          cat <<EOF > config/settings.yaml
          teams:
            webhook_url: "${{ secrets.TEAMS_WEBHOOK_URL }}"
          EOF

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Forecast Bot
        run: python src/fetch_forecast.py
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Commit updated CSV & seen_ids
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_pattern: |
            data/processed/filtered_forecast.csv
            data/processed/seen_ids.json
          commit_message: 'chore: update processed CSV and seen_ids'
          branch: main
          commit_user_name: 'github-actions'
          commit_user_email: 'github-actions@github.com'
