name: Daily Forecast Bot

on:
  schedule:
    # runs every weekday at 9 AM ET (13:00 UTC)
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # persist-credentials is true by default, so GITHUB_TOKEN can push back

      - name: Generate config/settings.yaml
        run: |
          mkdir -p config
          cat <<EOF > config/settings.yaml
          teams:
            webhook_url: "${{ secrets.TEAMS_WEBHOOK_URL }}"
          EOF

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Forecast Bot
        run: python src/fetch_forecast.py
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Commit updated CSV & seen_ids
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # commit only those two files
          file_pattern: |
            data/processed/filtered_forecast.csv
            data/processed/seen_ids.json
          commit_message: 'chore: update processed CSV and seen_ids'
          branch: main
          # use the inputs this action expects:
          commit_user_name: 'github-actions'
          commit_user_email: 'github-actions@github.com'
